name: Build and Release

on:
  push:
    tags:
      - 'v*'

permissions:
  id-token: write
  contents: write
  attestations: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Build for Linux
        run: make build-linux

      - name: Build for macOS
        run: make build-darwin

      - name: Generate artifact attestation for Linux binary
        uses: actions/attest-build-provenance@v2
        with:
          subject-path: s3-presigned-url-generator-linux-amd64

      - name: Generate artifact attestation for macOS binary
        uses: actions/attest-build-provenance@v2
        with:
          subject-path: s3-presigned-url-generator-darwin-arm64

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            s3-presigned-url-generator-linux-amd64
            s3-presigned-url-generator-darwin-arm64
          generate_release_notes: true 
